(test
 (name bootstrap_test)
 (libraries alcotest rationale_kernel))

(test
 (name protocol_test)
 (libraries alcotest rationale_kernel yojson))

(test
 (name kernel_test)
 (libraries alcotest rationale_kernel yojson))

(test
 (name properties_test)
 (libraries alcotest qcheck rationale_kernel yojson))
